import './layout_tree.dart';
import './workspace_models.dart';

/// Factory default workspace arrangements.
///
/// Auto-generated by WorkspaceStore.promoteToDefaults() — do not
/// edit by hand. To update, arrange the workspaces in the
/// app and use the 'Promote to defaults' developer button.
abstract final class DefaultLayouts {
  /// All factory default workspaces in order.
  static List<Workspace> all() => [
        flightControl(),
        preflightCheck(),
        recovery(),
        replay(),
        flightPath(),
      ];

  /// Flight control
  static Workspace flightControl() => Workspace(
    id: GridIds.next(),
    name: 'Flight control',
    root: SplitNode(
      vertical: false,
      ratio: 0.6666666666666666,
      a: SplitNode(
        vertical: false,
        ratio: 0.5,
        a: SplitNode(
          vertical: true,
          ratio: 0.5,
          a: LeafNode(tileId: GridIds.next(), tileType: 'rocket_3d'),
          b: LeafNode(tileId: GridIds.next(), tileType: 'map'),
        ),
        b: SplitNode(
          vertical: true,
          ratio: 0.5,
          a: SplitNode(
            vertical: true,
            ratio: 0.6666666666666666,
            a: SplitNode(
              vertical: false,
              ratio: 0.5,
              a: LeafNode(tileId: GridIds.next(), tileType: 'highlights'),
              b: LeafNode(tileId: GridIds.next(), tileType: 'events'),
            ),
            b: SplitNode(
              vertical: false,
              ratio: 0.49999999999999994,
              a: LeafNode(tileId: GridIds.next(), tileType: 'max_alt'),
              b: LeafNode(tileId: GridIds.next(), tileType: 'nosecone'),
            ),
          ),
          b: SplitNode(
            vertical: true,
            ratio: 0.3333333333333333,
            a: SplitNode(
              vertical: false,
              ratio: 0.49999999999999994,
              a: LeafNode(tileId: GridIds.next(), tileType: 'altitude_chart'),
              b: LeafNode(tileId: GridIds.next(), tileType: 'velocity_chart'),
            ),
            b: LeafNode(tileId: GridIds.next(), tileType: 'altitude_chart'),
          ),
        ),
      ),
      b: SplitNode(
        vertical: true,
        ratio: 0.5,
        a: LeafNode(tileId: GridIds.next(), tileType: 'fsm'),
        b: LeafNode(tileId: GridIds.next(), tileType: 'control_panel'),
      ),
    ),
  );

  /// Pre-flight check
  static Workspace preflightCheck() => Workspace(
    id: GridIds.next(),
    name: 'Pre-flight check',
    root: SplitNode(
      vertical: false,
      ratio: 0.5,
      a: SplitNode(
        vertical: false,
        ratio: 0.5,
        a: SplitNode(
          vertical: true,
          ratio: 0.49898451718407943,
          a: SplitNode(
            vertical: true,
            ratio: 0.3333333333333333,
            a: LeafNode(tileId: GridIds.next(), tileType: 'hall_sensor'),
            b: LeafNode(tileId: GridIds.next(), tileType: 'hall_sensor'),
          ),
          b: SplitNode(
            vertical: true,
            ratio: 0.3333333333333333,
            a: LeafNode(tileId: GridIds.next(), tileType: 'battery_chart'),
            b: LeafNode(tileId: GridIds.next(), tileType: 'battery_chart'),
          ),
        ),
        b: SplitNode(
          vertical: true,
          ratio: 0.49898451718407943,
          a: LeafNode(tileId: GridIds.next(), tileType: 'nosecone'),
          b: LeafNode(tileId: GridIds.next(), tileType: 'channel_health'),
        ),
      ),
      b: SplitNode(
        vertical: true,
        ratio: 0.49898451718407943,
        a: LeafNode(tileId: GridIds.next(), tileType: 'fsm'),
        b: LeafNode(tileId: GridIds.next(), tileType: 'control_panel'),
      ),
    ),
  );

  /// Recovery
  static Workspace recovery() => Workspace(
    id: GridIds.next(),
    name: 'Recovery',
    root: SplitNode(
      vertical: false,
      ratio: 0.5,
      a: SplitNode(
        vertical: true,
        ratio: 0.25,
        a: SplitNode(
          vertical: false,
          ratio: 0.5,
          a: LeafNode(tileId: GridIds.next(), tileType: 'stats'),
          b: LeafNode(tileId: GridIds.next(), tileType: 'dead_reckoning'),
        ),
        b: LeafNode(tileId: GridIds.next(), tileType: 'map'),
      ),
      b: LeafNode(tileId: GridIds.next(), tileType: 'flight_3d_sat'),
    ),
  );

  /// Replay
  static Workspace replay() => Workspace(
    id: GridIds.next(),
    name: 'Replay',
    root: SplitNode(
      vertical: false,
      ratio: 0.5,
      a: LeafNode(tileId: GridIds.next(), tileType: 'flight_3d_sat'),
      b: SplitNode(
        vertical: false,
        ratio: 0.5,
        a: SplitNode(
          vertical: true,
          ratio: 0.6666666666666666,
          a: SplitNode(
            vertical: true,
            ratio: 0.4952114924181964,
            a: LeafNode(tileId: GridIds.next(), tileType: 'altitude_chart'),
            b: LeafNode(tileId: GridIds.next(), tileType: 'velocity_chart'),
          ),
          b: LeafNode(tileId: GridIds.next(), tileType: 'acceleration_chart'),
        ),
        b: SplitNode(
          vertical: true,
          ratio: 0.6666666666666666,
          a: SplitNode(
            vertical: true,
            ratio: 0.4952114924181964,
            a: LeafNode(tileId: GridIds.next(), tileType: 'highlights'),
            b: LeafNode(tileId: GridIds.next(), tileType: 'events'),
          ),
          b: LeafNode(tileId: GridIds.next(), tileType: 'map'),
        ),
      ),
    ),
  );

  /// Flight path
  static Workspace flightPath() => Workspace(
    id: GridIds.next(),
    name: 'Flight path',
    root: LeafNode(tileId: GridIds.next(), tileType: 'flight_3d'),
  );
}
